spring:
  web:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}

aws:
  profile: ${AWS_PROFILE:default}
  region: ${AWS_REGION:fakeRegion}
  accessKeyId: ${AWS_ACCESS_KEY_ID:fakeMyKeyId}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY:fakeSecretAccessKey}
  dynamodb:
    endpoint: http://localhost:8000
  sns:
    email-topic-arn: ${EMAIL_SNS_TOPIC_ARN:'arn:aws:sns:us-west-2:627643173759:EmailNotifications'}
    sms-topic-arn: ${SMS_SNS_TOPIC_ARN:'arn:aws:sns:us-west-2:627643173759:SmsNotifications'}