service: lambda-service

provider:
  name: aws
  runtime: java17
  stage: dev
  region: ${env:AWS_REGION, 'us-west-2'}
  profile: ${env:AWS_PROFILE, 'default'}

functions:
  userHandler:
    handler: com.btg_pactual.interfaces.Application::handleRequest
    environment:
      AWS_REGION: ${self:provider.environment.AWS_REGION}
      AWS_PROFILE: ${self:provider.environment.AWS_PROFILE}
    events:
      - http:
          path: api/v1/users
          method: get
      - http:
          path: api/v1/users/{user_id}
          method: get
      - http:
          path: api/v1/users/{user_id}
          method: put
      - http:
          path: api/v1/users/{user_id}/reset
          method: put
      - http:
          path: api/v1/users/{user_id}/history
          method: get
  fundHandler:
    handler: com.btg_pactual.interfaces.Application::handleRequest
    environment:
      AWS_REGION: ${self:provider.environment.AWS_REGION}
      AWS_PROFILE: ${self:provider.environment.AWS_PROFILE}
    events:
      - http:
          path: api/v1/funds
          method: get
      - http:
          path: api/v1/funds/{fund_id}/subscribe
          method: post
      - http:
          path: api/v1/funds/{fund_id}/unsubscribe
          method: post

plugins:
  - serverless-java-maven
  - serverless-offline

package:
  exclude:
    - '**/test/**'
